sudo: required
language: elixir
elixir:
  - 1.8.1
otp_release:
  - '22.0.7'
script:
  - mix credo
  - "travis_wait 30 mix dialyzer --plt"
  - mix dialyzer --halt-exit-status
cache:
  - directories:
      - .dialyzer
