name: Move closed issue or pull request to Done

on:
  issues:
    types: [closed]
  pull_request:
    types: [closed]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/community.github-project-automation
        with:
          backend: https://integration-api.taxfix.de/api/github-project-automation/
          project: tax-engine
          column: Done
