name: Move open/reopened issue to To do

on:
  issues:
    types: [opened, reopened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/community.github-project-automation
        with:
          backend: https://integration-api.taxfix.de/api/github-project-automation/
          project: tax-engine
          column: To do
